apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
spec:
  selector:
    matchLabels:
      app: myweb
  replicas: 2
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - name: myweb
          image: kubelo1705/demo-docker
          ports:
            - containerPort: 8080
          envFrom:  
            - secretRef:
                name: app-config
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3006
          envFrom:
            - secretRef:
                name: mysql-config
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: pv-mysql
      volumes:
        - name: pv-mysql
          persistentVolumeClaim:
            claimName: pvc-mysql


